# Some people think alpine is not a good choice


# FROM python:3.7-alpine AS base
FROM python:3.11-alpine AS base

WORKDIR /weather

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Development Stage
FROM base AS develop
RUN pip install debugpy
# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE 1
# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED 1

# Production Stage
FROM base AS production
COPY . .
CMD ["sleep", "infinity"]